In [1]:
import pickle

with open("embeddings_output/embeddings_new_2_without_prop_afterpropparasent.pkl", "rb") as f:
    files = pickle.load(f)

In [2]:
files

,filename,set,query,cases,text,paragraphs,paragraphs_formatted,suppressed_sections,propositions,propositions_en,...,sentences_en_string,sentences_en_set,sentences_en_set_list,paragraphs_formatted_en_set_list,propositions_en_set_list,judge,year,embeddings_propositions_en,embeddings_paragraphs_formatted,embeddings_sentences_en
0,79311,train,False,[],"Strayer, J.\n: These are two applications unde...","[[2] In April and May, 1993 the Department of ...","[In April and May, 1993 the Department of the ...",[],[],[],...,april depart secretari state receiv request in...,"{oblig, wouldb, context, need, said, obstruct,...","[{secretari, servic, contract, state, individu...","[{delet, indic, repli, disclosur, identifi, hi...",[],None,1994,[],"[[-0.20004287, 0.10326447, -0.025002336, 0.010...","[[-0.06782752, 0.026452757, -0.044306185, -0.2..."
1,15880,train,False,[],"Federal Court\nFebruary 22, 2008. <FRAGMENT_S...",[[1] : This is an application for a judicial r...,[: This is an application for a judicial revie...,[],[],[],...,applic judici review decis visa offic date oct...,"{mysor, indic, skill, substitut, neg, short, m...","[{applic, refus, perman, date, decis, judici, ...","[{applic, refus, perman, date, decis, judici, ...",[],None,2008,[],"[[0.49238092, 0.21510422, -0.42108464, 0.05929...","[[0.47733235, 0.2424333, -0.4347535, 0.0768362..."
2,42979,train,False,[],"Federal Court\nAngus Grant, for the applicant;...",[[2] The guiding principle in respect of new e...,[The guiding principle in respect of new evide...,[],[],[],...,guid principl respect new evid submit preremov...,"{quash, neg, juli, lr, context, counsel, regul...","[{respect, state, risk, evid, principl, assess...","[{respect, state, risk, evid, principl, assess...",[],None,2009,[],"[[-0.11704859, 0.21959981, -0.21703193, 0.0462...","[[-0.109607965, 0.21841578, -0.19464128, -0.00..."
3,79847,train,False,[],MLB unedited judgment <FRAGMENT_SUPPRESSED>\n...,[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[],[],[],...,applic judici review decis convent refuge dete...,"{truck, indic, oblig, address, specif, neg, ju...","[{statu, determin, juli, judici, so, armenia, ...","[{truck, statu, left, march, determin, juli, j...",[],None,2002,[],"[[0.01899644, 0.25205392, -0.3343874, 0.293352...","[[0.23801307, 0.06658855, -0.508649, 0.1040462..."
4,76089,train,False,[],"Federal Court\nJanuary 18, 2010. <FRAGMENT_SU...",[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[],[],[],...,applic judici review pursuant subsect immigr r...,"{persuad, butt, arrest, indic, quash, specif, ...","[{deni, judici, subsect, alexand, april, sc, g...","[{deni, judici, subsect, alexand, april, sc, g...",[],None,2010,[],"[[0.13882422, 0.0042256033, -0.35483626, -0.03...","[[0.13882422, 0.0042256033, -0.35483626, -0.03..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9284,87439,test,True,[],"[1]\nO'Reilly, J.\n: The Minister of National ...","[[1] O'Reilly, J. : The Minister of National H...","[O'Reilly, J. : The Minister of National Healt...",[[6] A person who wishes to have a drug patent...,[A person who wishes to have a drug patent pro...,[A person who wishes to have a drug patent pro...,...,oreilli j minist nation health welfar deni bio...,"{essenc, regul, said, permit, interact, mosley...","[{medicin, protect, deni, welfar, patent, spec...","[{deni, regul, afford, nation, complianc, chal...","[{come, roch, holder, ingredi, regul, substanc...",O'Reilly,2005,"[[0.2033237, 0.07713017, -0.0013799854, -0.332...","[[0.034605406, 0.31155354, -0.18228303, -0.428...","[[-0.1733626, 0.27614993, -0.08298564, -0.2654..."
9285,56791,test,False,[],"[1]\n: When this matter first came before me, ...","[[1] : When this matter first came before me, ...","[: When this matter first came before me, I he...",[],[],[],...,matter came held sell deal certain line tobler...,"{oblig, motion, marilyn, guess, ra, repres, ne...","[{copyright, euro, tobleron, artist, sell, cer...","[{copyright, eleph, judgment, euro, noninfring...",[],None,2006,[],"[[-0.030241987, 0.11559475, 0.2913074, 0.07729...","[[-0.021545937, -0.25190827, 0.42281914, 0.097..."
9286,63269,test,False,[],[1]\n: Jesse C. Stine (Mr. Stine) accompanied ...,[[1] : Jesse C. Stine (Mr. Stine) accompanied ...,[The Affidavit filed by Mr. G. Stine confirms ...,[],[],[],...,jess c stine mr stine accompani father mr g st...,"{opportun, indic, vancouv, specif, address, ca...","[{canada, januari, stine, g, jess, move, c, fa...","[{car, stine, took, confirm, interview, have, ...",[],None,1999,[],"[[0.18088058, -0.13562658, 0.028819468, -0.019...","[[0.13282943, -0.21410841, -0.46067286, -0.131..."
9287,39286,test,False,[],<FRAGMENT_SUPPRESSED> CF 301)\nFederal Court\...,[[1] : Ms. Bergeron asks the Court to set asid...,[: Ms. Bergeron asks the Court to set aside tw...,[],[],[],...,ms bergeron ask court set asid decis canadian ...,"{correspond, quash, department, juli, great, c...","[{ask, address, set, paragraph, act, frivol, b...","[{ask, address, set, paragraph, act, frivol, b...",[],None,2010,[],"[[0.0004916121, 0.27729335, -0.15477355, 0.150...","[[0.0004919755, 0.27729362, -0.15477327, 0.150..."
9288,80537,test,False,[],"[1]\nHeald, D.J.\n: This is an appeal pursuant...","[[1] Heald, D.J. : This is an appeal pursuant ...","[Heald, D.J. : This is an appeal pursuant to s...",[],[],[],...,appeal pursuant s trademark act rsc c decis re...,"{swim, juli, counterstat, essenc, oppon, couns...","[{applic, impact, trademark, respond, appel, a...","[{reject, appeal, trademark, appel, act, heald...",[],Heald,1994,[],"[[-0.23222148, 0.1515877, 0.17087917, -0.28888...","[[-0.17638505, 0.21595688, 0.08042288, -0.3397..."

In [2]:
files = files.drop(columns=[
    'propositions',
    'propositions_en',
    'propositions_en_set_list',
    'embeddings_propositions_en'
])

In [4]:
files

,filename,set,query,cases,text,paragraphs,paragraphs_formatted,suppressed_sections,sentences,sentences_en,...,entity_string,entity_set,sentences_en_string,sentences_en_set,sentences_en_set_list,paragraphs_formatted_en_set_list,judge,year,embeddings_paragraphs_formatted,embeddings_sentences_en
0,79311,train,False,[],"Strayer, J.\n: These are two applications unde...","[[2] In April and May, 1993 the Department of ...","[In April and May, 1993 the Department of the ...",[],"[In April and May, 1993 the Department of the ...","[In April and May, 1993 the Department of the ...",...,departmentsecretary state accessinformationact...,"{, governmentcanada, french, courtappeal, depa...",april depart secretari state receiv request in...,"{issu, grill, paid, accept, s, paragraph, guar...","[{depart, request, individu, secretari, inform...","[{basi, came, disclos, ernest, eman, inform, r...",None,1994,"[[-0.20004287, 0.10326447, -0.025002336, 0.010...","[[-0.06782752, 0.026452757, -0.044306185, -0.2..."
1,15880,train,False,[],"Federal Court\nFebruary 22, 2008. <FRAGMENT_S...",[[1] : This is an application for a judicial r...,[: This is an application for a judicial revie...,[],[: This is an application for a judicial revie...,[: This is an application for a judicial revie...,...,visa applicant applicant applicant dubai perso...,"{court, regulations, personalbackground, ba, v...",applic judici review decis visa offic date oct...,"{school, abil, ask, track, issu, likelihood, a...","[{resid, decis, judici, visa, offic, applic, p...","[{resid, fact, decis, judici, visa, offic, app...",None,2008,"[[0.49238092, 0.21510422, -0.42108464, 0.05929...","[[0.47733235, 0.2424333, -0.4347535, 0.0768362..."
2,42979,train,False,[],"Federal Court\nAngus Grant, for the applicant;...",[[2] The guiding principle in respect of new e...,[The guiding principle in respect of new evide...,[],[The guiding principle in respect of new evide...,[The guiding principle in respect of new evide...,...,riskassessment prra prra immigrationrefugeepr...,"{, riskassessment, crdd, prra, respondent, per...",guid principl respect new evid submit preremov...,"{reject, issu, number, civil, accept, quash, s...","[{clearli, respect, assess, submit, prra, new,...","[{clearli, respect, assess, submit, prra, new,...",None,2009,"[[-0.11704859, 0.21959981, -0.21703193, 0.0462...","[[-0.109607965, 0.21841578, -0.19464128, -0.00..."
3,79847,train,False,[],MLB unedited judgment <FRAGMENT_SUPPRESSED>\n...,[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[],[: This is an application for judicial review ...,[: This is an application for judicial review ...,...,conventionrefugeedeterminationdivisionimmigrat...,"{, conventionrefugeedeterminationdivisionimmig...",applic judici review decis convent refuge dete...,"{school, region, reject, issu, septemb, lie, n...","[{decis, juli, so, judici, claim, date, statu,...","[{school, came, war, decis, truck, juli, septe...",None,2002,"[[0.01899644, 0.25205392, -0.3343874, 0.293352...","[[0.23801307, 0.06658855, -0.508649, 0.1040462..."
4,76089,train,False,[],"Federal Court\nJanuary 18, 2010. <FRAGMENT_SU...",[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[],[: This is an application for judicial review ...,[: This is an application for judicial review ...,...,immigrationrefugeeprotectionact punjab pakist...,"{, section, court, board, irb, lahore, fir, pa...",applic judici review pursuant subsect immigr r...,"{exert, readili, irb, understood, climat, reje...","[{decis, judici, claim, c, pursuant, act, refu...","[{decis, judici, claim, c, pursuant, act, refu...",None,2010,"[[0.13882422, 0.0042256033, -0.35483626, -0.03...","[[0.13882422, 0.0042256033, -0.35483626, -0.03..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9284,87439,test,True,[],"[1]\nO'Reilly, J.\n: The Minister of National ...","[[1] O'Reilly, J. : The Minister of National H...","[O'Reilly, J. : The Minister of National Healt...",[[6] A person who wishes to have a drug patent...,"[O'Reilly, J. : The Minister of National Healt...","[O'Reilly, J. : The Minister of National Healt...",...,nationalhealthwelfare biovail patentedmedicin...,"{, eli, canadian, court, patentedmedicines, bi...",oreilli j minist nation health welfar deni bio...,"{just, issu, number, payload, oreilli, essenc,...","[{j, patent, request, afford, notic, biovail, ...","[{patent, nation, decis, accord, oreilli, j, d...",O'Reilly,2005,"[[0.034605406, 0.31155354, -0.18228303, -0.428...","[[-0.1733626, 0.27614993, -0.08298564, -0.2654..."
9285,56791,test,False,[],"[1]\n: When this matter first came before me, ...","[[1] : When this matter first came before me, ...","[: When this matter first came before me, I he...",[],"[: When this matter first came before me, I he...","[: When this matter first came before me, I he...",...,toblerone kraft toblerone canada kraft canadia...,"{, courtappeal, infringement, kraft, australia...",matter came held sell deal certain line tobler...,"{confer, just, issu, forward, fee, will, shed,...","[{came, held, wrapper, deal, breach, matter, l...","[{came, damag, held, prime, wrapper, element, ...",None,2006,"[[-0.030241987, 0.11559475, 0.2913074, 0.07729...","[[-0.021545937, -0.25190827, 0.42281914, 0.097..."
9286,63269,test,False,[],[1]\n: Jesse C. Stine (Mr. Stine) accompanied ...,[[1] : Jesse C. Stine (Mr. Stine) accompanied ...,[The Affidavit filed by Mr. G. Stine confirms ...,[],[: Jesse C. Stine (Mr. Stine) accompanied his ...,[: Jesse C. Stine (Mr. Stine) accompanied his ...,...,canada emoryuniversity atlanta georgia canada ...,"{, atlanta, teitelbaum, citizenship, act, brit...",jess c stine mr stine accompani father mr g st...,"{stine, ask, block, inform, cabl, argument, ap...","[{stine, move, jess, father, c, g, januari, ca...","[{stine, locat, block, walk, car, confirm, res...",None,1999,"[[0.18088058, -0.13562658, 0.028819468, -0.019...","[[0.13282943, -0.21410841, -0.46067286, -0.131..."
9287,39286,test,False,[],<FRAGMENT_SUPPRESSED> CF 301)\nFederal Court\...,[[1] : Ms. Bergeron asks the Court to set asid...,[: Ms. Bergeron asks the Court to set aside tw...,[],[: Ms. Bergeron asks the Court to set aside tw...,[: Ms. Bergeron asks the Court to set aside tw...,...,court canadianhumanrightscommission canadianhu...,"{, lawsocietyuppercanada, secondcomplaint, dep...",ms bergeron ask court set asid decis canadian ...,"{f, reject, issu, forward, fee, will, bergeron...","[{decis, ms, ask, complaint, frivol, human, re...","[{decis, ms, ask, complaint, frivol, human, re...",None,2010,"[[0.0004916121, 0.27729335, -0.15477355, 0.150...","[[0.0004919755, 0.27729362, -0.15477327, 0.150..."
9288,80537,test,False,[],"[1]\nHeald, D.J.\n: This is an appeal pursuant...","[[1] Heald, D.J. : This is an appeal pursuant ...","[Heald, D.J. : This is an appeal pursuant to s...",[],[This is an appeal pursuant to s. 56(1) of the...,[This is an appeal pursuant to s. 56(1) of the...,...,act registrartrademarks dupont dupont registra...,"{, registrartrademarks, trademarks, act, stray...",appeal pursuant s trademark act rsc c decis re...,"{reject, issu, small, essenc, accept, s, parag...","[{s, decis, trademark, file, opposit, act, imp...","[{dj, decis, reject, registrar, appeal, du, re...",Heald,1994,"[[-0.23222148, 0.1515877, 0.17087917, -0.28888...","[[-0.17638505, 0.21595688, 0.08042288, -0.3397..."

In [ ]:
import pandas as pd
import pickle

# 1️⃣ Load the embeddings DataFrame
with open("embeddings_output/embeddings_new_2_with_prop_afterprop.pkl", "rb") as f:
    emb_df = pickle.load(f)

# 2️⃣ Select only the needed columns + filename
cols_to_add = ['filename', 'query',  'propositions', 'propositions_en', 'propositions_en_set_list', 'embeddings_propositions_en']
emb_df = emb_df[cols_to_add]
emb_df[emb_df['query']==True]

,filename,query,propositions,propositions_en,propositions_en_set_list,embeddings_propositions_en
13,067648,True,[The business practices of Laquerre and his no...,[The business practices of Laquerre and his no...,"[{easi, orthodox, compani, busi, describ, nona...","[[-0.08556327, 0.19617341, 0.026644152, 0.0746..."
17,004393,True,[The court is bound to follow a previous decis...,[The court is bound to follow a previous decis...,"[{follow, longer, unless, manifestli, decis, c...","[[0.21852942, -0.11995617, 0.05567759, -0.1700..."
25,050604,True,[A hearing conducted by an independent chairpe...,[A hearing conducted by an independent chairpe...,"[{quasijudici, conduct, judici, independ, proc...","[[0.17165485, -0.082904, 0.10237924, 0.0091609..."
28,005830,True,[Assistant Commissioner McCowan should have co...,[Assistant Commissioner McCowan should have co...,"[{rais, level, commission, mccowan, assist, is...","[[0.14690849, 0.085594825, 0.015604705, 0.0004..."
30,061349,True,[Deference should be granted to the Member in ...,[Deference should be granted to the Member in ...,"[{formal, grant, year, defer, fall, find, memb...","[[0.22063324, 0.042416234, -0.06441894, 0.0158..."
...,...,...,...,...,...,...
9250,023817,True,[The standard of review applicable to determin...,[The standard of review applicable to determin...,"[{reason, convent, refuge, standard, asylum, n...","[[-0.03281265, -0.21655138, -0.027477043, -0.1..."
9259,084834,True,"[Any attempt to prevent, fetter, or influence ...","[Any attempt to prevent, fetter, or influence ...","[{exercis, corrupt, right, constitut, result, ...","[[-0.09114416, 0.12722166, 0.042376444, 0.1015..."
9264,022841,True,[The issues raised in a judicial review are sy...,[The issues raised in a judicial review are sy...,"[{judici, similar, institut, court, interlocut...","[[0.20730329, 0.08226153, 0.041154068, 0.03149..."
9283,079911,True,[Where the Appeal Division has affirmed a deci...,[Where the Appeal Division has affirmed a deci...,"[{appeal, law, board, decis, court, ensur, aff...","[[0.002596125, -0.043676972, 0.034007106, 0.04..."
9284,087439,True,[A method of combining the active ingredients ...,[A method of combining the active ingredients ...,"[{combin, similar, activ, substanc, method, dr...","[[0.15676539, 0.07378287, -0.026583735, -0.063..."

In [4]:
del emb_df

In [3]:
import pandas as pd
import pickle

# 1️⃣ Load the embeddings DataFrame
with open("embeddings_output/embeddings_new_2_with_prop_afterprop.pkl", "rb") as f:
    emb_df = pickle.load(f)

# 2️⃣ Select only the needed columns + filename
cols_to_add = ['filename', 'propositions', 'propositions_en', 'propositions_en_set_list', 'embeddings_propositions_en']
emb_df = emb_df[cols_to_add]

# 3️⃣ Merge without converting to string
# Standardize filenames in both DataFrames
files['filename'] = files['filename'].astype(str).str.strip().str.zfill(6)
emb_df['filename'] = emb_df['filename'].astype(str).str.strip().str.zfill(6)

# Optional: remove duplicates in emb_df
emb_df = emb_df.drop_duplicates(subset='filename')

# Merge
files = files.merge(emb_df, on='filename', how='left')
files

,filename,set,query,cases,text,paragraphs,paragraphs_formatted,suppressed_sections,sentences,sentences_en,...,sentences_en_set_list,paragraphs_formatted_en_set_list,judge,year,embeddings_paragraphs_formatted,embeddings_sentences_en,propositions,propositions_en,propositions_en_set_list,embeddings_propositions_en
0,079311,train,False,[],"Strayer, J.\n: These are two applications unde...","[[2] In April and May, 1993 the Department of ...","[In April and May, 1993 the Department of the ...",[],"[In April and May, 1993 the Department of the ...","[In April and May, 1993 the Department of the ...",...,"[{depart, individu, secretari, translat, state...","[{depart, portion, ident, advis, request, gave...",None,1994,"[[-0.20004287, 0.10326447, -0.025002336, 0.010...","[[-0.06782752, 0.026452757, -0.044306185, -0.2...",[],[],[],[]
1,015880,train,False,[],"Federal Court\nFebruary 22, 2008. <FRAGMENT_S...",[[1] : This is an application for a judicial r...,[: This is an application for a judicial revie...,[],[: This is an application for a judicial revie...,[: This is an application for a judicial revie...,...,"[{perman, octob, decis, applic, date, review, ...","[{perman, octob, decis, applic, date, fact, re...",None,2008,"[[0.49238092, 0.21510422, -0.42108464, 0.05929...","[[0.47733235, 0.2424333, -0.4347535, 0.0768362...",[],[],[],[]
2,042979,train,False,[],"Federal Court\nAngus Grant, for the applicant;...",[[2] The guiding principle in respect of new e...,[The guiding principle in respect of new evide...,[],[The guiding principle in respect of new evide...,[The guiding principle in respect of new evide...,...,"[{guid, clearli, preremov, principl, risk, sta...","[{guid, clearli, preremov, principl, risk, sta...",None,2009,"[[-0.11704859, 0.21959981, -0.21703193, 0.0462...","[[-0.109607965, 0.21841578, -0.19464128, -0.00...",[],[],[],[]
3,079847,train,False,[],MLB unedited judgment <FRAGMENT_SUPPRESSED>\n...,[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[],[: This is an application for judicial review ...,[: This is an application for judicial review ...,...,"[{rsc, determin, refuge, base, immigr, claim, ...","[{discrimin, unit, attack, rsc, mother, march,...",None,2002,"[[0.01899644, 0.25205392, -0.3343874, 0.293352...","[[0.23801307, 0.06658855, -0.508649, 0.1040462...",[],[],[],[]
4,076089,train,False,[],"Federal Court\nJanuary 18, 2010. <FRAGMENT_SU...",[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[],[: This is an application for judicial review ...,[: This is an application for judicial review ...,...,"[{georg, pursuant, deni, alexand, refuge, prot...","[{georg, pursuant, deni, alexand, refuge, prot...",None,2010,"[[0.13882422, 0.0042256033, -0.35483626, -0.03...","[[0.13882422, 0.0042256033, -0.35483626, -0.03...",[],[],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9284,087439,test,True,[],"[1]\nO'Reilly, J.\n: The Minister of National ...","[[1] O'Reilly, J. : The Minister of National H...","[O'Reilly, J. : The Minister of National Healt...",[[6] A person who wishes to have a drug patent...,"[O'Reilly, J. : The Minister of National Healt...","[O'Reilly, J. : The Minister of National Healt...",...,"[{protect, biovail, minist, request, welfar, p...","[{biovail, minist, request, deni, regul, j, pr...",O'Reilly,2005,"[[0.034605406, 0.31155354, -0.18228303, -0.428...","[[-0.1733626, 0.27614993, -0.08298564, -0.2654...",[A method of combining the active ingredients ...,[A method of combining the active ingredients ...,"[{similar, activ, substanc, patent, creat, ing...","[[0.15676539, 0.07378287, -0.026583735, -0.063..."
9285,056791,test,False,[],"[1]\n: When this matter first came before me, ...","[[1] : When this matter first came before me, ...","[: When this matter first came before me, I he...",[],"[: When this matter first came before me, I he...","[: When this matter first came before me, I he...",...,"[{côte, copyright, excel, display, held, deal,...","[{desist, côte, award, copyright, judgment, de...",None,2006,"[[-0.030241987, 0.11559475, 0.2913074, 0.07729...","[[-0.021545937, -0.25190827, 0.42281914, 0.097...",[],[],[],[]
9286,063269,test,False,[],[1]\n: Jesse C. Stine (Mr. Stine) accompanied ...,[[1] : Jesse C. Stine (Mr. Stine) accompanied ...,[The Affidavit filed by Mr. G. Stine confirms ...,[],[: Jesse C. Stine (Mr. Stine) accompanied his ...,[: Jesse C. Stine (Mr. Stine) accompanied his ...,...,"[{januari, windsor, mr, c, accompani, jess, ca...","[{citizenship, block, interview, affidavit, ti...",None,1999,"[[0.18088058, -0.13562658, 0.028819468, -0.019...","[[0.13282943, -0.21410841, -0.46067286, -0.131...",[],[],[],[]
9287,039286,test,False,[],<FRAGMENT_SUPPRESSED> CF 301)\nFederal Court\...,[[1] : Ms. Bergeron asks the Court to set asid...,[: Ms. Bergeron asks the Court to set aside tw...,[],[: Ms. Bergeron asks the Court to set aside tw...,[: Ms. Bergeron asks the Court to set aside tw...,...,"[{vexati, remedi, asid, bergeron, dismiss, pur...","[{vexati, remedi, asid, bergeron, dismiss, pur...",None,2010,"[[0.0004916121, 0.27729335, -0.15477355, 0.150...","[[0.0004919755, 0.27729362, -0.15477327, 0.150...",[],[],[],[]
9288,080537,test,False,[],"[1]\nHeald, D.J.\n: This is an appeal pursuant...","[[1] Heald, D.J. : This is an appeal pursuant ...","[Heald, D.J. : This is an appeal pursuant to s...",[],[This is an appeal pursuant to s. 56(1) of the...,[This is an appeal pursuant to s. 56(1) of the...,...,"[{pont, reject, applic, respond, rsc, appeal, ...","[{reject, dj, rsc, appeal, pursuant, heald, re...",Heald,1994,"[[-0.23222148, 0.1515877, 0.17087917, -0.28888...","[[-0.17638505, 0.21595688, 0.08042288, -0.3397...",[],[],[],[]

In [4]:
files[files['query']==True]

,filename,set,query,cases,text,paragraphs,paragraphs_formatted,suppressed_sections,sentences,sentences_en,...,sentences_en_set_list,paragraphs_formatted_en_set_list,judge,year,embeddings_paragraphs_formatted,embeddings_sentences_en,propositions,propositions_en,propositions_en_set_list,embeddings_propositions_en
13,067648,train,True,"[057864.txt, 015217.txt, 022958.txt, 044714.tx...","[1]\n[Translation]: As a general rule, pursuan...","[[1] [Translation]: As a general rule, pursuan...","[[Translation]: As a general rule, pursuant to...","[[18] After the impugned order was issued, the...","[[Translation]: As a general rule, pursuant to...","[[Translation]: As a general rule, pursuant to...",...,"[{incom, translat, rsc, supp, gener, tax, rule...","[{collect, believ, rsc, minist, reason, rule, ...",None,2008,"[[-0.093921185, 0.42223734, -0.07770487, 0.174...","[[-0.29727143, 0.10337745, 0.074214265, -0.100...",[The business practices of Laquerre and his no...,[The business practices of Laquerre and his no...,"[{orthodox, easi, practic, trust, laquerr, mak...","[[-0.08556327, 0.19617341, 0.026644152, 0.0746..."
17,004393,train,True,"[010556.txt, 066923.txt, 020848.txt, 027924.txt]",[1]\n: The present Application is focused on a...,[[1] : The present Application is focused on a...,[: The present Application is focused on an in...,[[3] On the issue of the correct interpretatio...,[: The present Application is focused on an in...,[: The present Application is focused on an in...,...,"[{applic, immigr, present, appeal, focus, inte...","[{limit, written, appeal, reason, rule, interp...",None,2024,"[[0.30908164, 0.16601478, 0.04332332, -0.41533...","[[0.26691514, 0.14824839, -0.059351865, -0.338...",[The court is bound to follow a previous decis...,[The court is bound to follow a previous decis...,"[{manifestli, flaw, unless, longer, consid, qu...","[[0.21852942, -0.11995617, 0.05567759, -0.1700..."
25,050604,train,True,[059832.txt],<FRAGMENT_SUPPRESSED> (TD)\n[French language ...,[[1] [Translation]: This application for judic...,[[Translation]: This application for judicial ...,[[7] In regard to the principles governing dis...,[[Translation]: This application for judicial ...,[[Translation]: This application for judicial ...,...,"[{octob, applic, set, translat, chairperson, d...","[{sentenc, asid, institut, disciplinari, parag...",None,2002,"[[0.19883408, 0.3446586, -0.36825556, -0.04299...","[[0.16160823, 0.38824347, -0.48511723, -0.1055...",[A hearing conducted by an independent chairpe...,[A hearing conducted by an independent chairpe...,"[{hear, independ, chairperson, institut, quasi...","[[0.17165485, -0.082904, 0.10237924, 0.0091609..."
28,005830,train,True,[024935.txt],"Wilson v. Can. (A.G.) (2012), 403 F.T.R. 287 (...","[[1] Mactavish, J. : Karl Wilson seeks judicia...","[Mactavish, J. : Karl Wilson seeks judicial re...",[[22] Mr. Wilson relies on the decision in TAR...,"[Mactavish, J. : Karl Wilson seeks judicial re...","[Mactavish, J. : Karl Wilson seeks judicial re...",...,"[{wilson, mccowan, assist, commission, review,...","[{level, deni, j, assist, judici, mccowan, com...",Mactavish,2012,"[[-0.39214414, -0.08575122, -0.39883465, 0.026...","[[-0.38532507, 0.117149875, -0.3067382, -0.014...",[Assistant Commissioner McCowan should have co...,[Assistant Commissioner McCowan should have co...,"[{mccowan, assist, rais, consid, commission, l...","[[0.14690849, 0.085594825, 0.015604705, 0.0004..."
30,061349,train,True,"[030014.txt, 050995.txt, 037198.txt, 074698.tx...","Federal Court\nOctober 15, 2008.\nMichael Korm...",[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[[9] The Supreme Court of Canada in <TARGETCAS...,[: This is an application for judicial review ...,[: This is an application for judicial review ...,...,"[{pursuant, determin, refuge, protect, immigr,...","[{psb, republ, pursuant, determin, china, refu...",None,2008,"[[0.20155406, 0.15713984, -0.4922654, 0.158862...","[[0.3223025, 0.10668644, -0.66653556, 0.118759...",[Deference should be granted to the Member in ...,[Deference should be granted to the Member in ...,"[{defer, year, applic, outcom, establish, find...","[[0.22063324, 0.042416234, -0.06441894, 0.0158..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9250,023817,test,True,[],"Federal Court\nFebruary 9, 2007.\nJean-Françoi...",[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,"[[7] <TARGETCASE> Justice Blanchard found, aft...",[: This is an application for judicial review ...,[: This is an application for judicial review ...,...,"[{find, pursuant, refuge, protect, immigr, sc,...","[{find, fact, pursuant, refuge, protect, immig...",None,2007,"[[-0.03168432, 0.041215055, -0.60971904, 0.109...","[[-0.037846588, 0.047708943, -0.6310884, 0.110...",[The standard of review applicable to determin...,[The standard of review applicable to determin...,"[{applic, standard, nexu, simplicit, review, a...","[[-0.03281265, -0.21655138, -0.027477043, -0.1..."
9259,084834,test,True,[],"Federal Court\nPriscilla Kennedy, for the appl...",[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[: This is an application for judicial review ...,...,"[{bouchier, kelsey, march, gladu, candid, mcke...","[{bouchier, band, kelsey, march, council, memb...",None,2012,"[[-0.022353001, -0.36177173, 0.14185473, 0.204...","[[-0.00959273, -0.31846988, 0.09570573, 0.1607...","[Any attempt to prevent, fetter, or influence ...","[Any attempt to prevent, fetter, or influence ...","[{influenc, corrupt, affect, practic, improper...","[[-0.09114416, 0.12722166, 0.042376444, 0.1015..."
9264,022841,test,True,[],"[1]\n: As a rule, this Court is not inclined t...","[[1] : As a rule, this Court is not inclined t...","[: As a rule, this Court is not inclined to ju...","[[1] : As a rule, this Court is not inclined t...","[: As a rule, this Court is not inclined to ju...","[: As a rule, this Court is not inclined to ju...",...,"[{feder, tribun, interlocutori, review, rule, ...","[{decisionmak, end, judgment, prevent, dismiss...",None,2010,"[[0.1084839, 0.080706, -0.23328698, 0.0516628,...","[[0.21750796, 0.19526987, -0.354682, -0.008847...",[The issues raised in a judicial review are sy...,[The issues raised in a judicial review are sy...,"[{rais, similar, order, institut, way, canadia...","[[0.20730329, 0.08226153, 0.041154068, 0.03149..."
9283,079911,test,True,[],[1]\n: This is an application for judicial rev...,[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[[17] Although the matter before this Court is...,[: This is an application for judicial review ...,[: This is an application for judicial review ...,...,"[{board, decis, applic, appeal, review, judici...","[{fact, appeal, reason, deni, time, relev, set...",None,2014,"[[0.19103849, 0.008736679, -0.14753462, 0.0097...","[[0.12906443, -0.2181897, -0.40126446, -0.0921...",[Where the Appeal Division has affirmed a deci...,[Where the Appeal Division has affirmed a deci...,"[{board, law, appeal, ensur, affirm, decis, di...","[[0.002596125, -0.043676972, 0.034007106, 0.04..."
9284,087439,test,True,[],"[1]\nO'Reilly, J.\n: The Minister of National ...","[[1] O'Reilly, J. : The Minister of National H...","[O'Reilly, J. : The Minister of National Healt...",[[6] A person who wishes to have a drug patent...,"[O'Reilly, J. : The Minister of National Healt...","[O'Reilly, J. : The Minister of National Healt...",...,"[{protect, biovail, minist, request, welfar, p...","[{biovail, minist, request, deni, regul, j, pr...",O'Reilly,2005,"[[0.034605406, 0.31155354, -0.18228303, -0.428...","[[-0.1733626, 0.27614993, -0.08298564, -0.2654...",[A method of combining the active ingredients ...,[A method of combining the active ingredients ...,"[{similar, activ, substanc, patent, creat, ing...","[[0.15676539, 0.07378287, -0.026583735, -0.063..."

In [5]:
import pickle 
filename = 'embeddings_output/embeddings_new_2_with_prop_afterpropparasent.pkl'

with open(filename, 'wb') as f:
    pickle.dump(files, f)
print("Saved pickle: ", filename)

Saved pickle:  embeddings_output/embeddings_new_2_with_prop_afterpropparasent.pkl

In [7]:
# del files
del emb_df

In [ ]:
files

,filename,set,query,cases,text,paragraphs,paragraphs_formatted,suppressed_sections,sentences,sentences_en,...,sentences_en_set_list,paragraphs_formatted_en_set_list,judge,year,embeddings_paragraphs_formatted,embeddings_sentences_en,propositions,propositions_en,propositions_en_set_list,embeddings_propositions_en
0,79311,train,False,[],"Strayer, J.\n: These are two applications unde...","[[2] In April and May, 1993 the Department of ...","[In April and May, 1993 the Department of the ...",[],"[In April and May, 1993 the Department of the ...","[In April and May, 1993 the Department of the ...",...,"[{depart, request, individu, secretari, inform...","[{basi, came, disclos, ernest, eman, inform, r...",None,1994,"[[-0.20004287, 0.10326447, -0.025002336, 0.010...","[[-0.06782752, 0.026452757, -0.044306185, -0.2...",NaN,NaN,NaN,NaN
1,15880,train,False,[],"Federal Court\nFebruary 22, 2008. <FRAGMENT_S...",[[1] : This is an application for a judicial r...,[: This is an application for a judicial revie...,[],[: This is an application for a judicial revie...,[: This is an application for a judicial revie...,...,"[{resid, decis, judici, visa, offic, applic, p...","[{resid, fact, decis, judici, visa, offic, app...",None,2008,"[[0.49238092, 0.21510422, -0.42108464, 0.05929...","[[0.47733235, 0.2424333, -0.4347535, 0.0768362...",NaN,NaN,NaN,NaN
2,42979,train,False,[],"Federal Court\nAngus Grant, for the applicant;...",[[2] The guiding principle in respect of new e...,[The guiding principle in respect of new evide...,[],[The guiding principle in respect of new evide...,[The guiding principle in respect of new evide...,...,"[{clearli, respect, assess, submit, prra, new,...","[{clearli, respect, assess, submit, prra, new,...",None,2009,"[[-0.11704859, 0.21959981, -0.21703193, 0.0462...","[[-0.109607965, 0.21841578, -0.19464128, -0.00...",NaN,NaN,NaN,NaN
3,79847,train,False,[],MLB unedited judgment <FRAGMENT_SUPPRESSED>\n...,[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[],[: This is an application for judicial review ...,[: This is an application for judicial review ...,...,"[{decis, juli, so, judici, claim, date, statu,...","[{school, came, war, decis, truck, juli, septe...",None,2002,"[[0.01899644, 0.25205392, -0.3343874, 0.293352...","[[0.23801307, 0.06658855, -0.508649, 0.1040462...",NaN,NaN,NaN,NaN
4,76089,train,False,[],"Federal Court\nJanuary 18, 2010. <FRAGMENT_SU...",[[1] : This is an application for judicial rev...,[: This is an application for judicial review ...,[],[: This is an application for judicial review ...,[: This is an application for judicial review ...,...,"[{decis, judici, claim, c, pursuant, act, refu...","[{decis, judici, claim, c, pursuant, act, refu...",None,2010,"[[0.13882422, 0.0042256033, -0.35483626, -0.03...","[[0.13882422, 0.0042256033, -0.35483626, -0.03...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9284,87439,test,True,[],"[1]\nO'Reilly, J.\n: The Minister of National ...","[[1] O'Reilly, J. : The Minister of National H...","[O'Reilly, J. : The Minister of National Healt...",[[6] A person who wishes to have a drug patent...,"[O'Reilly, J. : The Minister of National Healt...","[O'Reilly, J. : The Minister of National Healt...",...,"[{j, patent, request, afford, notic, biovail, ...","[{patent, nation, decis, accord, oreilli, j, d...",O'Reilly,2005,"[[0.034605406, 0.31155354, -0.18228303, -0.428...","[[-0.1733626, 0.27614993, -0.08298564, -0.2654...",NaN,NaN,NaN,NaN
9285,56791,test,False,[],"[1]\n: When this matter first came before me, ...","[[1] : When this matter first came before me, ...","[: When this matter first came before me, I he...",[],"[: When this matter first came before me, I he...","[: When this matter first came before me, I he...",...,"[{came, held, wrapper, deal, breach, matter, l...","[{came, damag, held, prime, wrapper, element, ...",None,2006,"[[-0.030241987, 0.11559475, 0.2913074, 0.07729...","[[-0.021545937, -0.25190827, 0.42281914, 0.097...",NaN,NaN,NaN,NaN
9286,63269,test,False,[],[1]\n: Jesse C. Stine (Mr. Stine) accompanied ...,[[1] : Jesse C. Stine (Mr. Stine) accompanied ...,[The Affidavit filed by Mr. G. Stine confirms ...,[],[: Jesse C. Stine (Mr. Stine) accompanied his ...,[: Jesse C. Stine (Mr. Stine) accompanied his ...,...,"[{stine, move, jess, father, c, g, januari, ca...","[{stine, locat, block, walk, car, confirm, res...",None,1999,"[[0.18088058, -0.13562658, 0.028819468, -0.019...","[[0.13282943, -0.21410841, -0.46067286, -0.131...",NaN,NaN,NaN,NaN
9287,39286,test,False,[],<FRAGMENT_SUPPRESSED> CF 301)\nFederal Court\...,[[1] : Ms. Bergeron asks the Court to set asid...,[: Ms. Bergeron asks the Court to set aside tw...,[],[: Ms. Bergeron asks the Court to set aside tw...,[: Ms. Bergeron asks the Court to set aside tw...,...,"[{decis, ms, ask, complaint, frivol, human, re...","[{decis, ms, ask, complaint, frivol, human, re...",None,2010,"[[0.0004916121, 0.27729335, -0.15477355, 0.150...","[[0.0004919755, 0.27729362, -0.15477327, 0.150...",NaN,NaN,NaN,NaN
9288,80537,test,False,[],"[1]\nHeald, D.J.\n: This is an appeal pursuant...","[[1] Heald, D.J. : This is an appeal pursuant ...","[Heald, D.J. : This is an appeal pursuant to s...",[],[This is an appeal pursuant to s. 56(1) of the...,[This is an appeal pursuant to s. 56(1) of the...,...,"[{s, decis, trademark, file, opposit, act, imp...","[{dj, decis, reject, registrar, appeal, du, re...",Heald,1994,"[[-0.23222148, 0.1515877, 0.17087917, -0.28888...","[[-0.17638505, 0.21595688, 0.08042288, -0.3397...",NaN,NaN,NaN,NaN